### ISSUE TITLE
Error while doing the test

### ISSUE THREAD

**Issue by Sid9993** [Gaochengzhi/Platoon#2]
Hi there,
I've tried to run the first example as shown in the readme file which is:
`LV=0.3 NV=3 VSUM=1200 MPRS-0.5 python3 main.py
`![image](https://github.com/Gaochengzhi/Platoon/assets/75777345/ed09b7bf-0a5e-4f6c-ba0f-f421c42ddaa1)
But this error is coming and also after running the simulation I'm getting a folder named:`6000|0.5|3|0.3`
The SUMO windows is like this:
![image](https://github.com/Gaochengzhi/Platoon/assets/75777345/9939a380-e02a-44c5-9e2a-d41a5234e386)

Can you please guide me on how to resolve the issue?

**Comment by Gaochengzhi** [comment]
mkdir cfg/data

**Comment by Sid9993** [comment]
> change w into w+

Hi thanks for replying, but after changing it the error is still there.
I changed it from w to w+ and I ran the program again using the command `LV=0.3 NV=3 VSUM=1200 MPRS-0.5 python3 main.py`
It is giving the same error.
![image](https://github.com/Gaochengzhi/Platoon/assets/75777345/222f84fa-266c-4cd1-89c7-9b002667842d)

**Comment by Gaochengzhi** [comment]
email me

**Comment by Sid9993** [comment]
> Can you please guide me on how to resolve the issue?
Ok Taitan I have sent the mail.

**Comment by Sid9993** [comment]
> mkdir cfg/data

Thank u Taitan.
